version: "3.9"

services:
  integration:
    build:
      context: ..
      dockerfile: integration/Dockerfile
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - smartware_net

networks:
  smartware_net:
    external: true
    name: smartware_net
